### ISSUE TITLE
Hound should describe what "atx heading format" means

### ISSUE THREAD

**Issue by sikachu** [houndci/hound#1058]
I got a warning from Hound today:

```
Headings should use atx
```

It took me a while to understand what that means, and I think it would be nicer if we add a link to [Markdown documentation](https://daringfireball.net/projects/markdown/syntax#header) for atx format, or reword the suggestion altogether. (Maybe "Use # symbol for heading" instead.)

**Comment by teoljungberg** [comment]
Hound doesn't modify any of the messages, they are made by the underlaying linters we are using. In the case of markdown, we are using [remark-lint](https://github.com/wooorm/remark-lint).

Markdown is currently not documented, because we are still battle testing it internally. But, it will be [documented](https://houndci.com/configuration) as the the other linters. And the ATX heading format is explained in that [documentation](https://github.com/wooorm/remark/blob/d1c52a3b28223e55aef9067ab725330019c87aae/doc/remarksetting.7.md#closed-atx-headings)
