### ISSUE TITLE
Linters for Atom, Sublime Text, etc.

### ISSUE THREAD

**Issue by leo** [houndci/hound#1082]
Wouldn't it be awesome to have linter add-ons called "hound" (the name is [available](https://atom.io/packages/hound)) for a few editors? This would allow contributors to check their styles locally before committing something.

After that, hound's automated service will check the PR to make sure that the contributor hasn't ignored/overlooked any errors.

And the coolest part about that: Those local linters could even respect the contents of the `.hound.yml` file and therefore represent a complete local counterpart to your service (however, they will still only work together, since PRs still need to be checked for errors).

**Comment by thorncp** [comment]
@leo Thanks for submitting this request!

I think it's a great idea. We have talked about this internally a few times, but it always ends up being lower priority than other tasks. A few reasons I think that is case are:

* It's not feasible for the local "hound" linter to utilize the houndci.com service, because the delay in feedback would be unacceptable. If we stay entirely local, we can't guarantee what versions of the language linters are available, which will lead to instability around API changes (there's probably some smart things we can do to ease the pains there).
* I think everyone on the Hound team uses Vim, so interest in maintaining plugins for other editors will likely be low.
* It doesn't directly increase the experience of the houndci.com service

I would love to see this come to fruition, but for now I think it'll just stay on the radar :satellite:

**Comment by puranjayjain** [comment]
@leo not that I oppose this idea but there is already great support for linters on atom. Not so sure about atom.
Reference:
https://atom.io/packages/linter
https://atom.io/packages/search?q=linter

I personally use linters for scss and coffeescript in my projects

**Comment by leo** [comment]
@puranjayjain Sure! But those linters don't respect hound's code styling (which can also be configured through special files within the repo).

**Comment by puranjayjain** [comment]
@leo I agree to you on this but there is a little workaround for them e.g in coffeescript I renamed the file to coffeelint.json to get it working with atom's linter as well as hound.

**Comment by leo** [comment]
@puranjayjain Ahh, interesting! :blush:

However, this doesn't seem like a sustainable approach to me. The linters would have to detect both files then, because renaming something would make it a change that needs to be committed. And in turn, committing it to the repo, will make it unreadable for hound...

**Comment by puranjayjain** [comment]
@leo well that's the trade-off we have here unfortunately. 
What I think could be a possible solution be:
The linters over at atom must have an option to change the name of the default linter file which can be exposed via the config.

**Comment by leo** [comment]
@puranjayjain Yep, that's a good idea!

**Comment by puranjayjain** [comment]
@leo can you open an issue [there](https://github.com/AtomLinter/linter-coffeelint/issues) and reference this issue over there? I'll send a PR if there is a positive response :grin:

**Comment by leo** [comment]
@puranjayjain Sorry, but I honestly don't like CoffeeScript at all... 😅

**Comment by puranjayjain** [comment]
@leo I just remembered you can also do [this](https://github.com/puranjayjain/chrome-color-picker/blob/master/.hound.yml#L4) :disappointed_relieved:

**Comment by gylaz** [comment]
Looks like there is a workaround for Atom, to rename the files to what atom wants, then configure the new filename in `.hound.yml`.

Hound team isn't likely to want to support Atom or Sublime Text directly.

**Comment by leo** [comment]
Haha, awesome! 😂
