### ISSUE TITLE
Config mismatch between rubocop 0.37.2 and .ruby-style.yml

### ISSUE THREAD

**Issue by joshlory** [houndci/hound#1083]
The version of [rubocop specified in Gemfile.lock](https://github.com/houndci/hound/blob/626408cd5b81989fcb66471ffa4b1b1391905339/Gemfile.lock#L289) doesn't support [Style/TrailingComma in .ruby-style.yml](https://github.com/houndci/hound/blob/626408cd5b81989fcb66471ffa4b1b1391905339/.ruby-style.yml#L424-L431):

```
$ bundle exec rubocop
Error: The `Style/TrailingComma` cop no longer exists. Please use `Style/TrailingCommaInLiteral` and/or `Style/TrailingCommaInArguments` instead.
```

Thanks!

**Comment by dcarral** [comment]
Weird, since the [docs](https://houndci.com/configuration) state that [this config] (https://raw.githubusercontent.com/houndci/hound/master/config/style_guides/ruby.yml) (adapted to latest RuboCop versions) is used by default (if no custom config. file is specified).

In addition, I'm not being able to get Hound CI to work with repos with updated RuboCop configuration files. Most of the time Hound doesn't even analyze the PRs, and when it does it freezes with a "busy reviewing changes" message.

**Comment by joshlory** [comment]
Aha, I was looking at the wrong config file.  Thank you!

I will validate that Hound CI works on our repo with the updated config & then close this issue.
