### ISSUE TITLE
Doesn't allow owners of organizations to use Hound

### ISSUE THREAD

**Issue by dijonkitchen** [houndci/hound#1217]
I'm the owner (thus admin) of an organization, but I can't use Hound on a public repo. 

I tried refreshing and manually making myself an admin on the team of collaborators, but it still didn't work.

**Comment by gylaz** [comment]
This is likely caused by the fact that HoundCI does not have access to the organization. You can go to https://github.com/settings/applications then click on HoundCI and make sure the access is granted.

If your problem still exists, reach out to us via the help widget on houndci.com and we'll be able to look into your issue.

**Comment by dijonkitchen** [comment]
Wonderful! I saw that access was granted to Hound, but I needed to click into more detailed settings per organization and grant access. Thanks!
