### ISSUE TITLE
Option to support a single comment (versus multiple comments)

### ISSUE THREAD

**Issue by Fryguy** [houndci/hound#1236]
One problem for our team with HoundCI is that a contributor's PR will get lots of individual comments for things they may introduce since HoundCI comments on each individual issue.  Each of these individual comments also creates a separate email.

Before HoundCI came out we had created a bot that does linting checks, but comments with a single comment.  I would love to get rid of our bot and switch to HoundCI, but this is the one feature that prevents us from moving over.

Here is a screenshot of an example comment that our bot does

<img width="1148" alt="manageiq 2016-10-25 12-23-47" src="https://cloud.githubusercontent.com/assets/52120/19694669/43e020b2-9aae-11e6-937f-1ac647dc7be1.png">

**Comment by gylaz** [comment]
Thanks for the idea! This is likely will be something we'll look into once GitHub opens up their new Review API. Closing for now.

**Comment by jaydorsey** [comment]
Can this be re-opened/re-visited? The new API has, I believe, been released. One comment (that gets updated) instead of dozens and dozens of comments that keep reposting every time a new PR is force-pushed (after the comment has been silenced) makes code reviews difficult

(Fixing the issues immediately isn't always an option in this scenario)
