### ISSUE TITLE
CSS Grid property `grid-column-gap` not recognized

### ISSUE THREAD

**Issue by samkap** [houndci/hound#1523]
Error which appears: 
![screenshot 2018-04-10 11 47 22](https://user-images.githubusercontent.com/2152574/38571036-016e7620-3cb5-11e8-8b57-697f9cf98f0b.png)

[MDN docs on `grid-column-gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-gap)

**Comment by gylaz** [comment]
Which CSS linter are you using?

**Comment by samkap** [comment]
@gylaz a scss-lint one, which just wasn't updated to include grid-column-gap. Fixed.

**Comment by gylaz** [comment]
@samkap curious, was it a setting in `scss-lint`, or do we need to update our version of `scss-lint`?

**Comment by mikefogg** [comment]
Hey @gylaz, I know this is a bit old now, but did you ever end up seeing what the issue was here? I'm getting a `Unknown property grid-gap` issue on houndci.

Looks like it should be in `scss-lint` https://github.com/brigade/scss-lint/blob/91471531ff5afe09e1a928272e04d98f34a27535/data/properties.txt?
