### ISSUE TITLE
Unable to resolve path to module 'react' import/no-unresolved

### ISSUE THREAD

**Issue by cvjude** [houndci/hound#1739]
I have this problem with hound-ci while using React, I have integrated hound with eslint in my hound.yml file

My config
```
 eslint:
  enabled: true
  config_file: .eslintrc.json
```

I have also added some plugins to my eslint.json file

My eslint config
```
{
	"env": {
		"browser": true,
		"es6": true,
		"jest": true
	},
	"extends": "airbnb",
	"globals": {
		"Atomics": "readonly",
		"SharedArrayBuffer": "readonly"
	},
	"parser": "babel-eslint",
	"parserOptions": {
		"ecmaFeatures": {
			"jsx": true,
			"arrowFunctions": true
		},
		"ecmaVersion": 2018,
		"sourceType": "module"
	},
	"plugins": [
		"react",
		"import"
	],
	"rules": {
		"react/jsx-filename-extension": [1, {
			"extensions": [".js", ".jsx"]
		}],
		"react/prefer-stateless-function": 0,
		"react/jsx-props-no-spreading": 0,
		"import/no-useless-path-segments": 0,
		"arrow-parens": 0,
		"import/extensions": "off",
		"react/forbid-prop-types": 0,
		"react/no-array-index-key": 0,
		"react/no-did-update-set-state": 0,
		"import/no-extraneous-dependencies": [2, {
			"devDependencies": ["**/*.test.js", "**/*.spec.js", "src/setupTests.js", "build-utils/*"]
		}],
		"one-var": 0,
		"one-var-declaration-per-line": 0,
		"new-cap": 0,
		"consistent-return": 0,
		"no-param-reassign": 0,
		"comma-dangle": 2,
		"no-console": 2,
		"class-methods-use-this": 0,
		"curly": ["error", "multi-line"],
		"import/no-unresolved": "off",
		"import/no-named-as-default": 0,
		"no-shadow": ["error", {
			"allow": ["req", "res", "err"]
		}]
	}
}
```

Eslint does not flag an issue on my local code base
But on push I have large violations
despite my configurations
Please I need some help on this
It does the same for Enzyme and Redux

**Comment by gylaz** [comment]
Do you see this error on a specific line? Can you post a screenshot of what you're seeing?

**Comment by schuylr** [comment]
@cvjude You're getting bit by the [no-unresolved](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md) ESLint import plugin.

Your config doesn't look right for that particular rule, as you put:

```
"import/no-unresolved": "off",
```

and it should probably be `"import/no-unresolved": 0,` instead.

@gylaz Hound probably doesn't run an `npm install` or `yarn install`, which in conjunction with a gitignored `node_modules` folder would trigger this rule. Will Hound be able to allow npm/yarn installs as a pre-check hook for this plugin? Otherwise, I'll have to make a separate base `.eslintrc.js` file.

**Comment by gylaz** [comment]
@schuylr Hound does not run installs per each repo/build. We have pre-installed/whitelisted NPM packages on our end. We actually disable `import/no-unresolved` on our end, because of this.
