### ISSUE TITLE
Whilelist rubocop-performance for Rubocop 0.80+

### ISSUE THREAD

**Issue by gbp** [houndci/hound#1782]
In https://github.com/mysociety/alaveteli/pull/5585 we're seeing similar issue to #1718 but for Rubocop 0.80+. Please could this be whitelisted. Thanks

**Comment by gylaz** [comment]
`rubocop-performance` has been included in all RuboCop versions since `0.68.0`.
Perhaps something else is going on in your case... ah, I see, you have both `ruby` and `rubocop` in your `.hound.yml` but Hound expects only one (`ruby` being legacy). Combine the two under `rubocop` and you should be good.
