### ISSUE TITLE
Simplify configuration

### ISSUE THREAD

**Issue by salbertson** [houndci/hound#576]
Configuring Hound can be confusing at times. In order to configure Hound for Ruby you need to know how rules are [configured by default](https://github.com/thoughtbot/hound/blob/master/config/style_guides/ruby.yml) in Hound. You also need to know how rules are configured by default in RuboCop, since Hound inherits the default RuboCop config and overrides many of its defaults. This isn't ideal and has caused confusion in the past.

It might be simpler for teams to build their own config file based on their preferences, or even better choose a prebuilt one provided by Hound as a starting point that is based on a [common style guide](https://github.com/thoughtbot/guides/tree/master/style/ruby). This config would be the single source of truth and determine which rules Hound follows for a specific language. There wouldn't be any inherited defaults requiring extra knowledge to understand.

What do you think? Have you run into any issues configuring Hound?

Any suggestions or feedback would be great!

**Comment by salbertson** [comment]
Here's the branch I started making changes on, https://github.com/thoughtbot/hound/compare/sa-simpler-configuration.

Here's what I've done so far:

- Removed dependency on `hound.yml`. If you want Hound to check Ruby then all you need to do is create `.ruby-style.yml` in your project root directory.
- Removed cascading default RuboCop rules and default Hound rules. With this change you don't need to know which rules are enabled by RuboCop or Hound. The only rules that are enabled are in `.ruby-style.yml`, simple.

@gylaz, let me know what you think.

**Comment by croaky** [comment]
Interesting. Is that first file saying that users can and should build a whitelist, so to speak, of the rules they want? So you start with nothing and then build up just the ones you want?

**Comment by croaky** [comment]
Will we need to keep that `config/style_guides/ruby.yml` file updated from Rubocop? Is there a different way to "zero-initialize" it?

**Comment by salbertson** [comment]
> Is that first file saying that users can and should build a whitelist, so to speak, of the rules they want? So you start with nothing and then build up just the ones you want?

Yea, exactly.

> Will we need to keep that config/style_guides/ruby.yml file updated from Rubocop? Is there a different way to "zero-initialize" it?

Yea, we would have to keep that up to date with the the current version of RuboCop but we can cut a lot of it out. It's not there to enable or disable rules, just provide an outline for options and do some basic file exclusion.

**Comment by croaky** [comment]
What we talked about today was that each organization ends up with a Ruby, JavaScript, CoffeeScript, and SCSS config at the organization level. A little UI with a text box where they can edit their config. It would be "flat", not "how is this merging with the default?" questions. The UI would not have any toggle switches or anything for us to maintain. It'd have validation, though, when saved, so the user knows immediately if they have a syntax error or bad config setting.

We'd migrate the existing data, doing the merge one final time to generate the complete config per org. For each new repo as they come in, we'd copy the config over to their org's record. We'd be able to eliminate the current thoughtbot-specific config.

**Comment by salbertson** [comment]
That sounds like a good plan. The validation seems important since invalid configs are a source of frustration for some users since it's not very clear when the config is invalid.

What about when a team needs a different configuration for a single repo under the org? Are we planning on addressing that or not?

**Comment by croaky** [comment]
We were thinking we'd start with org config, and then see how often people ask for repo-level config. If it's super-rare, we might not need to support it, or could delay focus on it in exchange for other things. Felt we learn more by going org-only first.

**Comment by salbertson** [comment]
@croaky, there's has been feedback for both org level configuration and repo level configuration. It sounds like starting with org level is a deal breaker for some.

**Comment by srt32** [comment]
Once we have org level config server side, it doesn't seem like a large leap to support repo level config (perhaps using org level as the default but allowing for repo level if the user prefers). Can we start with org level and then move to optional repo level some time later?

**Comment by croaky** [comment]
Talk about it in-person tomorrow?

**Comment by srt32** [comment]
:+1:

**Comment by salbertson** [comment]
:+1:

**Comment by salbertson** [comment]
@srt32, would you outline what we talked about in person?

**Comment by srt32** [comment]
Here's what we concluded in the last conversation:

```
- Store org level config on the server (editable by users via browser)
- If a repo wants changes, merge in repo config files (containing overrides) with the org level config (on server)
- Have a less opinionated default config
```

Could I clarify further? @salbertson

**Comment by zmoazeni** [comment]
I came to the repo to post a question/comment but this seems like the relevant thread for it.

We use hound on our application and some of us like having the flexibility of running rubocop before we submit a pull request to reduce the github comment noise when possible. I completely understand and agree with the comment on [the FAQ](https://houndci.com/faq) for "Can I have Hound check my entire repository for style?".

That said we have to do some weird things to our rubocop config in order to have rubocop and hound report with the same set of rules. Currently we're copying over the ruby.yml from this repo into ours and referencing it from our rubocop.yml.

With the direction of moving the config to the server as an organization config, would that still be possible? Is there an easier way to sanity check some things locally?

**Comment by tansaku** [comment]
Our team has been confused by the difference between rubocop and hound defaults.  At the moment we are overriding hound defaults using .hound.yml pointing to a local .rubocop.yml on a repo by repo basis; but I'd much prefer to point to a single company "style file".  

Could hound.yml be adjusted to take a url rather than a file for the config_file option?

That would allow us to seriously DRY things out across repos ...

**Comment by mejackreed** [comment]
:+1: @tansaku

**Comment by tansaku** [comment]
still loving the idea of a hound URL rubocop config.  Also, by the way, is there any way to configure hound so that it will take the -DS flags so that the violation names and links to their explanation would appear in the pull request comments?

**Comment by tf** [comment]
I also imported the Hound default config into our project to align my local Rubocop checks with those run by Hound on PRs.

Reading that from a URL would definitely reduce duplication. Still it would require internet access to run checks, right? 

My first thought was that it would be great if Rubocop could take the Hound default config from some kind of `hound-rubocop-styles` gem, which could be a development dependency. It might be possible to extend Rubocop to also inherit config from files in gem directories. That way also an organizations style guide could be packaged up as a gem. Still, even if this mechanism existed, I don't think having Hound install arbitrary gems to read config from would be a secure thing from a deployment viewpoint.

**Comment by tansaku** [comment]
@tf is there any downside of internet access being required to run checks?  CI runs in the cloud with always on internet, so is there any disadvantage?

Although having the style guide in a gem is a nice idea too.

**Comment by tf** [comment]
Well, only if I want to run checks locally while i.e. sitting on a train. Maybe Rubocop could cache the file. But using a gem really just seems like a nice fit to handle these "transport" details.

**Comment by tansaku** [comment]
I'm often on the train myself, but there when I run rubocop it hits my local conf file.  I talking about having a URL in the .hound.yml  - I don't run hound on the train myself. Do you?  I guess maybe if you are developing hound itself?  I haven't tried that ...

But I guess gem is a better solution since the styleguide can be published once in gem form and then imported and effectively cached for ease of use wherever ... but that requires adjustments to how both hound and rubocop work ... wouldn't it be more practical in the first instance just to create the option to have a URL in the .hound.yml file ...

**Comment by tf** [comment]
I'm not sure I follow. I thought the point was not having to place a complete Rubocop config file in the repo. If there is a local Rubocop config file available, why not let hound also use that? I agree, though, that modifying Rubocop and Hound and solving the security issue around having Hound install gems to obtain config might not be realistic.

**Comment by tansaku** [comment]
On the train rubocop can hit my local conf file in my home dir.  

My use case is for lots of projects and a single style guide.  Rather than adding a single rubocop file to each project, the rubocop file is published on a public URL (e.g. a single style repo on github for the organisation perhaps) and then hound can pull it in for running CI on each of the projects.  If I need to run that single rubocop file locally it can be in my home dir (where all projects will pick it up).  The hope is to DRY things out so that when the organization style guide changes, all incoming pull requests on all repos will automatically be using the style guide.

**Comment by grantovich** [comment]
@croaky @salbertson Curious if there has been any discussion on this since February 2015 (I notice the `sa-simpler-configuration` branch has since been deleted). As far as I can tell, Hound still merges custom configuration into its own defaults, which themselves are overrides of the Rubocop defaults. In my current project, the `.rubocop.yml` is now 50 lines of meaningful customization, and 70 lines of "counter-overrides" to make Hound behave like stock Rubocop. Keeping up with two overlapping layers of defaults is certainly more difficult than one.

**Comment by gylaz** [comment]
@grantovich We still intend to remove Hound's defaults. We believe that once we support org-level config it will be easier for us to do that.

**Comment by grantovich** [comment]
@gylaz Thanks, we'll watch this space (unless there's a newer/related issue we should be tracking).

**Comment by teoljungberg** [comment]
@grantovich We'll update this issue as we know more.

**Comment by dcarral** [comment]
Thanks in advance @teoljungberg for keeping us posted. This would be a great step forward for Hound regarding the RuboCop integration ;)

**Comment by printercu** [comment]
Does hound use its own config even if I set `config_file: .rubocop.yml`? 
Here is PR: https://github.com/printercu/rails_stuff/pull/2 
Local rubocop doesn't show any warnings but hound does. I think this not not what most people do expect.

I think it'll also be great if hound could automatically detect if `.rubocop.yml` is present and use it without `config_file: .rubocop.yml`.

**Comment by grantovich** [comment]
@printercu The contents of your `config_file` are merged into Hound's [default config](https://github.com/houndci/hound/blob/master/config/style_guides/ruby.yml), which is different from Rubocop's default config. [As I mentioned above](https://github.com/houndci/hound/issues/576#issuecomment-176414707), it's currently a bit of work to make Hound and local Rubocop behave the same with the same config file. On one of my projects, instead of using Hound we run `rubocop` as a CI step (and have CI pass/fail linked to GitHub), which has made things a bit easier.

**Comment by printercu** [comment]
@grantovich Thank you! Sorry, I've missed your past answer first.

**Comment by dcarral** [comment]
@teoljungberg Do you know if there any plans/intentions to fix this issue by simply relying on the RuboCop configuration file provided by the user?

**Comment by teoljungberg** [comment]
@dcarral There is a plan to use the defaults - sorry it has taken so long.
But we want to existing users of Hound to have the same behavior even after the change to avoid any confusion in their usage.

**Comment by dcarral** [comment]
Sounds good. Any idea on when will this plan be executed? 

Feel free to ping me if you need help with it. We're really looking forward to get rid of all the _let's-make-Hound-use-RuboCop-as-it-should-by-default_ content in our RuboCop configuration files.

**Comment by arxpoetica** [comment]
@salbertson @gylaz update?

**Comment by gylaz** [comment]
We are still working to simplify the configuration. New customers currently don't inherit from Hound's defaults and get to use the linter defaults. Existing users can reach out to us via the help widget and we can set that up for them. There is also functionality (back-end only for now) for inheriting configuration from another repo, like https://github.com/houndci/legacy-config. We'll be exposing this feature in the UI soon.
