### ISSUE TITLE
Are there plans to support remote URLs in inherit_from?

### ISSUE THREAD

**Issue by awendt** [houndci/hound#996]
Rubocop supports [a full URL to a remote file](https://github.com/bbatsov/rubocop#inheriting-configuration-from-a-remote-url) as config since 0.35.0.

I just realized that Hound [parses `inherit_from` itself](https://github.com/thoughtbot/hound/blob/master/app/models/config/ruby.rb#L19-L26) (why?), so my question is: Are there plans to support this anytime soon?

**Comment by thorncp** [comment]
Interesting. Hound isn't on 0.35.0 yet, so I don't think anyone has thought of it. It's definitely a possibility, though.

As for why Hound parses `inherit_from` itself, it's because we have to fetch the files from GitHub. We don't clone your repo, so we don't have file system access to the inherited file like Rubocop expects. That's obviously a different story with an absolute URL, so we may be able to fallback to Rubocop's implementation for those cases.

Thanks for pointing this out.

**Comment by rmeritz** [comment]
It looks like Rubocop has been updated to `0.39.0` now https://github.com/houndci/hound/blob/master/Gemfile.lock#L288

However, the `inherit_from` feature of Rubocop still isn't working. I've tested it using an absolute url and it still seems to be ignoring the styles in that file. 

I'm unclear if it is not working because it isn't able to download the file from the url or if it because the merging of configs done buy hound causes styles specified in the file refereed to in the remote url to be ignored.

In any case it would be useful it it did work. It would a flexible way to have shared styles guides across an organization which is a problem I see you are trying to solve here:  https://github.com/houndci/hound/issues/576

**Comment by samtgarson** [comment]
+1 for this. Are there any plans in the works to support for this? If not I'll happily take a stab at it.

**Comment by gylaz** [comment]
We are working on an organization-wide configuration, that can be shared amongst repos. This will be in support of all linters, not just Ruby (so unrelated to urls in `inherit_from`).

**Comment by bradleypriest** [comment]
I've been looking around to check, does Hound still not support `inherit_from:` with URLs?
Or has this been added?
