### ISSUE TITLE
Re-comment if the line has changed, but the issue wasn't resolved

### ISSUE THREAD

**Issue by dkniffin** [houndci/hound#997]
### Flow to reproduce the issue

- Create a PR with a hound issue
- (Hound will comment on the line)
- Modify the line, but don't fix the issue
- Push
- Hound still fails, with the same comment, but you can't see it because it's in an out-dated diff.

### Expected behavior

If the line changed, and it still has an issue, hound should re-comment.

### Possible fix

I did some sleuthing, and I believe the issue is [this method](https://github.com/thoughtbot/hound/blob/master/app/models/file_review.rb#L27).

````ruby
def find_or_build_violation(line)
  violations.detect { |violation| violation.line_number == line.number } ||
    violations.build(line_number: line.number)
end
````

I'm not 100% how to fix it, but I think it should be something like:

````ruby
def find_or_build_violation(line)
  violations.detect { |violation| violation.line_number == line.number && ! violation.outdated? } || 
    violations.build(line_number: line.number)
end
````

The hard part though, is figuring out if the violation is outdated. Perhaps the github api has something for checking this? I might investigate this more and see if I can submit a PR.

**Comment by thorncp** [comment]
This was discussed a bit in the [Hound public Slack](https://houndci.slack.com/archives/houndci/p1449009535000063) channel. I'll try to summarize:

* GitHub does not provide a "comment hidden" attribute in their comments API.
* Hound reviews entire pull requests every time (versus commit by commit), which makes it difficult to determine if an existing violation was re-introduced in a new commit.
* A solution will very likely require the commit patch at comment-time, which currently isn't possible because Hound does not store it anywhere.

Did I miss anything?

**Comment by dkniffin** [comment]
I think that was everything we discussed.

I also thought a bit more on this last night. What if we did something like:

````ruby
  def find_or_build_violation(line)
    violation = find_violation(line)
    if violation.nil? || line.changed_since?(violation.sha)
      violations.build(line_number: line.number)
    end
  end

  def find_violation(line)
    violations.detect { |violation| violation.line_number == line.number }
  end
````

The two things here that we don't have are:
1) `violation.sha` - I think this would just mean adding a column to the violations table, and saving the sha when the violation is created, right? 
2) `line.changed_since?(sha)` - I'm still trying to think through this part, but maybe we could determine this from the set of patches in the PR? Right now we don't have easy access to those, but with a little refactoring I think we could.

Thoughts?

**Comment by gylaz** [comment]
@dkniffin Thanks for thinking this through. I'd like to clarify some information about your points:

> 1) violation.sha - I think this would just mean adding a column to the violations table, and saving the sha when the violation is created, right? 

This is already stored in the `builds` table, and every violation is ultimately part of a build.

> 2) line.changed_since?(sha) - I'm still trying to think through this part, but maybe we could determine this from the set of patches in the PR? Right now we don't have easy access to those, but with a little refactoring I think we could.

We chose not to store patches, because part of Hound's goal is not to ever store any of the code. We likely can still fetch the old patch and compare it vs the new.

The easies thing that I could think of, is to compare the body of the current comment vs the new. If the body doesn't match, then we comment again. This will not catch if the violation is truly new, but is the same violation message. Still, this might work for 95% of the cases.

**Comment by dkniffin** [comment]
That makes sense. So it'd be:

````ruby
 def find_or_build_violation(line)
    existing_violation = find_violation(line)
    new_violation = violations.build(line_number: line.number)
    if existing_violation.present? && existing_violation.message == new_violation.message
      existing_violation
    else
      new_violation
    end
  end

  def find_violation(line)
    violations.detect { |violation| violation.line_number == line.number }
  end
````

Just so it's clear, that would build violations for every file, every time. Will that reduce performance by much?

**Comment by thorncp** [comment]
The current approach is already building violations for every file and every build, so I think that example wouldn't have a noticeable impact on performance.

However, this example is given outside of the context of the calling method, `build_violation`, which [mutates the violation's message](https://github.com/thoughtbot/hound/blob/e01e2b0706596ef29fd1ea546e7f4d210f574bcb/app/models/file_review.rb#L8) immediately after `find_or_build_violation` is executed. We can't make a comparison of the `message` values for the two violations until after that mutation happens.

Additionally, `build_violation` is called for each line:message pair, so it may be invoked multiple times for the same violation object (e.g. two different rules violated on the same source line). This would result in the violation being mutated multiple times, meaning any incremental `message` comparison we make would not have seen the whole picture. We'd have to wait until _all_ messages have been added, which makes the `find_or_build_violation` an inappropriate place for this logic.

**Comment by gylaz** [comment]
This is how GitHub detects changes on PRs, and even if Hound re-commented GitHub would still show the comment thread as collapsed.
